import type { EffectConfig, EffectId, EffectParams } from '../types/effects';

export const baseDefaults: EffectParams = {
  patternInvert: false,
  innerGlowIntensity: 0,
  innerGlowRange: 0,
  innerGlowEdgeRange: 0,
  innerGlowCenter: true,
  innerGlowColor: '#ffffff',
  innerGlowOpacity: 0,
  innerGlowSize: 0,
  innerGlowChoke: 0,
  innerGlowSource: 'center',
  innerGlowRangeAmount: 1,
  innerGlowCenterX: 50,
  innerGlowCenterY: 50,
  innerGlowGamma: 1,
  innerGlowBlendMode: 'normal',
  contrast: 0,
  randomSeed: 314,
  roughness: 0,
  roughSmoothing: 0,
  roughRelative: true,
  roughSmoothPoints: true,
  lineDensity: 0,
  coarseGrainAmount: 0,
  lineAngle: 0,
  grainSize: 0,
  pathAmount: 0,
  cornerAmount: 0,
  traceFill: true,
  traceIgnoreWhite: false,
  textureIntensity: 0,
  textureScale: 100,
  textureInvert: false,
  textureThreshold: 0,
  tornEdgeStrength: 0,
  tornEdgeDetail: 0,
};

export const effectConfigs: Record<EffectId, EffectConfig> = {
  roughEngraving: {
    id: 'roughEngraving',
    name: '粗糙铜版刻印',
    description: '黑色图案、中心模糊内发光、粗糙边缘与铜版细颗粒刻印。',
    defaults: { ...baseDefaults },
    parameters: [
      { key: 'rough-glow', label: '1 内发光', kind: 'section' },
      { key: 'innerGlowColor', label: '颜色', kind: 'color' },
      { key: 'innerGlowOpacity', label: '透明度', kind: 'range', min: 0, max: 1, step: 0.01 },
      { key: 'innerGlowSize', label: '尺寸', kind: 'range', min: 0, max: 180, step: 1, unit: 'px' },
      { key: 'innerGlowCenterX', label: '中心 X', kind: 'range', min: 0, max: 100, step: 1, unit: '%' },
      { key: 'innerGlowCenterY', label: '中心 Y', kind: 'range', min: 0, max: 100, step: 1, unit: '%' },
      { key: 'rough-distort', label: '2 粗糙化', kind: 'section' },
      { key: 'grainSize', label: '大小', kind: 'range', min: 0, max: 2, step: 0.01, unit: '%' },
      { key: 'roughness', label: '细节', kind: 'range', min: 0, max: 20, step: 0.01, unit: '/英寸' },
      { key: 'rough-copper', label: '3 铜版雕刻', kind: 'section' },
      { key: 'lineDensity', label: '细颗粒数量', kind: 'range', min: 0, max: 100, step: 1, unit: '%' },
      { key: 'coarseGrainAmount', label: '粗颗粒数量', kind: 'range', min: 0, max: 100, step: 1, unit: '%' },
      { key: 'randomSeed', label: '随机纹理', kind: 'seed' },
    ],
  },
  tornTextureEngraving: {
    id: 'tornTextureEngraving',
    name: '撕边肌理刻印',
    description: '双层图案合成，肌理阈值遮罩与噪声撕边共同切削边缘。',
    defaults: { ...baseDefaults },
    parameters: [
      { key: 'torn-glow', label: '1 内发光', kind: 'section' },
      { key: 'innerGlowColor', label: '颜色', kind: 'color' },
      { key: 'innerGlowOpacity', label: '透明度', kind: 'range', min: 0, max: 1, step: 0.01 },
      { key: 'innerGlowSize', label: '尺寸', kind: 'range', min: 0, max: 180, step: 1, unit: 'px' },
      { key: 'innerGlowCenterX', label: '中心 X', kind: 'range', min: 0, max: 100, step: 1, unit: '%' },
      { key: 'innerGlowCenterY', label: '中心 Y', kind: 'range', min: 0, max: 100, step: 1, unit: '%' },
      { key: 'torn-texture-upload', label: '2 上传肌理', kind: 'section' },
      { key: 'texture-upload', label: '上传肌理', kind: 'textureUpload' },
      { key: 'textureIntensity', label: '肌理强度', kind: 'range', min: 0, max: 1, step: 0.01 },
      { key: 'textureScale', label: '肌理缩放', kind: 'range', min: 20, max: 400, step: 1, unit: '%' },
      { key: 'textureInvert', label: '肌理反相', kind: 'toggle' },
      { key: 'textureThreshold', label: '肌理阈值', kind: 'range', min: 0, max: 1, step: 0.01 },
      { key: 'torn-texture', label: '3 撕边肌理', kind: 'section' },
      { key: 'tornEdgeStrength', label: '撕边强度', kind: 'range', min: 0, max: 1, step: 0.01 },
      { key: 'tornEdgeDetail', label: '撕边细节', kind: 'range', min: 0, max: 1, step: 0.01 },
      { key: 'randomSeed', label: '随机纹理', kind: 'seed' },
    ],
  },
};

export const getDefaultParams = (effectId: EffectId): EffectParams => ({
  ...effectConfigs[effectId].defaults,
});
